"""Hook installation across every shape a hook-binding library can produce.

Git invokes exactly one file per hook, so the install has one job: be the
second line of that file, whatever the library put in it. These tests build
each library's real layout — husky v9's two-level delegation, lefthook's and
pre-commit's generated `exec`, simple-git-hooks' inline commands, overcommit's
shared symlink — and assert the same install works on all of them without the
manager knowing any of their names.
"""

import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

from iris.hooks import manager


HOOK = manager.HOOK_NAME
PUSH_HOOK = manager.POST_COMMIT_HOOK_NAME


@pytest.fixture(autouse=True)
def iris_home(tmp_path, monkeypatch):
    """Point IRIS_HOME at a scratch directory so payloads and the registry
    never touch the developer's real ~/.iris."""
    home = tmp_path / "iris-home"
    monkeypatch.setenv("IRIS_HOME", str(home))
    return home


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=repo, capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def _init(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    _git(path, "init", "-q", ".")
    _git(path, "config", "user.email", "test@iris.invalid")
    _git(path, "config", "user.name", "Iris Test")
    return path


def _write(path: Path, content: str, executable: bool = True) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    if executable:
        path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return path


# --- One builder per hook-binding library ------------------------------------


def _plain(tmp_path: Path) -> Path:
    """A repository with no hook library at all."""
    return _init(tmp_path / "plain")


def _handwritten(tmp_path: Path) -> Path:
    """A hand-rolled hook ending in `exit 0` — the classic dead-append trap."""
    repo = _init(tmp_path / "handwritten")
    _write(
        repo / ".git" / "hooks" / HOOK,
        '#!/bin/sh\necho "handwritten hook"\nexit 0\n',
    )
    return repo


def _husky_v9(tmp_path: Path) -> Path:
    """husky v9: core.hooksPath at .husky/_, stubs sourcing a runner that exits."""
    repo = _init(tmp_path / "husky9")
    _write(
        repo / ".husky" / "_" / "h",
        '#!/usr/bin/env sh\n'
        '[ "$HUSKY" = "0" ] && exit 0\n'
        'h="$(basename "$0")"\n'
        's="$(dirname "$(dirname "$0")")/$h"\n'
        '[ -f "$s" ] && sh "$s" "$@"\n'
        "exit $?\n",
    )
    for name in (HOOK, PUSH_HOOK):
        _write(repo / ".husky" / "_" / name, '#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n')
        _write(repo / ".husky" / name, f'#!/usr/bin/env sh\necho "public .husky/{name}"\n')
    _git(repo, "config", "core.hooksPath", ".husky/_")
    return repo


def _pre_commit(tmp_path: Path) -> Path:
    """pre-commit: a generated bash hook in .git/hooks that execs its binary."""
    repo = _init(tmp_path / "precommit")
    _write(
        repo / ".git" / "hooks" / HOOK,
        "#!/usr/bin/env bash\n"
        "# File generated by pre-commit: https://pre-commit.com\n"
        "ARGS=(hook-impl --hook-type=prepare-commit-msg)\n"
        'echo "pre-commit hook-impl"\n'
        "exit 0\n",
    )
    return repo


def _lefthook(tmp_path: Path) -> Path:
    """lefthook: a checksummed generated hook that execs `lefthook run`."""
    repo = _init(tmp_path / "lefthook")
    _write(
        repo / ".git" / "hooks" / HOOK,
        "#!/bin/sh\n"
        "# lefthook_version=1.7.0 reserved_for_lefthook\n"
        'echo "lefthook run"\n'
        "exec true\n",
    )
    return repo


def _simple_git_hooks(tmp_path: Path) -> Path:
    """simple-git-hooks: the configured command written inline."""
    repo = _init(tmp_path / "sgh")
    _write(
        repo / ".git" / "hooks" / HOOK,
        '#!/bin/sh\necho "simple-git-hooks"\nexit 0\n',
    )
    return repo


def _overcommit(tmp_path: Path) -> Path:
    """overcommit: every hook symlinked to one runner that dispatches on $0."""
    repo = _init(tmp_path / "overcommit")
    runner = _write(
        repo / "overcommit-hook",
        '#!/bin/sh\necho "overcommit dispatch: $(basename "$0")"\n',
    )
    for name in (HOOK, PUSH_HOOK):
        link = repo / ".git" / "hooks" / name
        link.parent.mkdir(parents=True, exist_ok=True)
        os.symlink(runner, link)
    return repo


def _custom_hooks_path(tmp_path: Path) -> Path:
    """A library pointing core.hooksPath at its own directory."""
    repo = _init(tmp_path / "hookspath")
    _write(repo / "ci-hooks" / HOOK, '#!/bin/sh\necho "custom dir hook"\nexit 0\n')
    _git(repo, "config", "core.hooksPath", "ci-hooks")
    return repo


BINDERS = {
    "plain": _plain,
    "handwritten-exit-0": _handwritten,
    "husky-v9": _husky_v9,
    "pre-commit": _pre_commit,
    "lefthook": _lefthook,
    "simple-git-hooks": _simple_git_hooks,
    "overcommit-symlink": _overcommit,
    "custom-hookspath": _custom_hooks_path,
}


@pytest.fixture(params=sorted(BINDERS), ids=sorted(BINDERS))
def binder_repo(request, tmp_path):
    return BINDERS[request.param](tmp_path)


# --- Slot resolution ---------------------------------------------------------


def test_hooks_dir_matches_what_git_reports(binder_repo):
    reported = _git(binder_repo, "rev-parse", "--git-path", "hooks")
    expected = os.path.abspath(os.path.join(binder_repo, reported))

    assert manager.resolve_hooks_dir(str(binder_repo)) == expected


def test_global_hooks_path_is_honoured(tmp_path, monkeypatch):
    repo = _init(tmp_path / "globalcase")
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    (fake_home / ".gitconfig").write_text(
        f"[core]\n\thooksPath = {tmp_path / 'global-hooks'}\n"
    )
    monkeypatch.setenv("HOME", str(fake_home))

    assert manager.resolve_hooks_dir(str(repo)) == str(tmp_path / "global-hooks")


def test_worktree_is_a_repository(tmp_path):
    repo = _init(tmp_path / "wt-main")
    _git(repo, "commit", "-q", "--allow-empty", "-m", "init")
    _git(repo, "worktree", "add", "-q", str(tmp_path / "wt"))

    assert (tmp_path / "wt" / ".git").is_file()
    assert manager.resolve_git_dir(str(tmp_path / "wt")) is not None
    assert manager.resolve_hooks_dir(str(tmp_path / "wt")) is not None


def test_non_repository_is_rejected(tmp_path):
    plain = tmp_path / "not-a-repo"
    plain.mkdir()

    assert manager.resolve_hooks_dir(str(plain)) is None
    with pytest.raises(FileNotFoundError):
        manager.install(str(plain))


# --- Reachability ------------------------------------------------------------


def test_install_is_reachable_on_every_binder(binder_repo):
    manager.install(str(binder_repo))

    assert manager.probe_reachable(str(binder_repo), HOOK)
    assert manager.status(str(binder_repo))["installed"]


def test_push_hook_is_reachable_on_every_binder(binder_repo):
    manager.install_push_hook(str(binder_repo))

    assert manager.probe_reachable(str(binder_repo), PUSH_HOOK)


def test_section_lands_at_the_top_of_the_file(binder_repo):
    hook_file = Path(manager.install(str(binder_repo)))
    lines = hook_file.read_text().split("\n")

    assert lines[0].startswith("#!")
    assert lines[1] == manager.HOOK_MARKER_START


def test_probe_reports_unreachable_when_section_is_stranded(binder_repo):
    hook_file = Path(manager.install(str(binder_repo)))
    content = hook_file.read_text()
    section_start = content.index(manager.HOOK_MARKER_START)
    section_end = content.index(manager.HOOK_MARKER_END) + len(manager.HOOK_MARKER_END)
    section = content[section_start:section_end]
    stranded = content[:section_start] + content[section_end:] + "\nexit 0\n" + section
    hook_file.write_text(stranded)

    assert not manager.probe_reachable(str(binder_repo), HOOK)
    assert not manager.status(str(binder_repo))["installed"]
    assert str(hook_file) in manager.status(str(binder_repo))["unreachable_sections"]


def test_probe_does_not_run_the_hook_below_it(tmp_path):
    repo = _init(tmp_path / "sideeffect")
    witness = tmp_path / "side-effect-ran"
    _write(
        repo / ".git" / "hooks" / HOOK,
        f'#!/bin/sh\ntouch "{witness}"\n',
    )
    manager.install(str(repo))

    assert manager.probe_reachable(str(repo), HOOK)
    assert not witness.exists()


@pytest.mark.parametrize("payload_present", [True, False])
def test_loader_survives_errexit(tmp_path, iris_home, payload_present):
    """A library may run its hook under errexit, where a top-level non-zero
    command aborts the script — and aborting prepare-commit-msg aborts the
    commit. The loader must fall through either way, payload or not."""
    repo = _init(tmp_path / f"errexit-{payload_present}")
    _write(repo / ".git" / "hooks" / HOOK, '#!/bin/sh -e\necho "library hook"\n')

    hook_file = manager.install(str(repo))
    if not payload_present:
        (iris_home / "hooks" / HOOK).unlink()

    (repo / "msg").write_text("subject\n")
    result = subprocess.run(
        [hook_file, str(repo / "msg"), "message"],
        cwd=repo,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert "library hook" in result.stdout


def test_probe_honours_the_shebang(tmp_path):
    """A bash-only hook must not be judged by running it under sh."""
    if shutil.which("bash") is None:
        pytest.skip("bash not available")

    repo = _init(tmp_path / "bashonly")
    _write(
        repo / ".git" / "hooks" / HOOK,
        "#!/usr/bin/env bash\nARGS=(one two)\necho \"${ARGS[0]}\"\n",
    )
    manager.install(str(repo))

    assert manager.probe_reachable(str(repo), HOOK)


# --- The existing hook keeps working ----------------------------------------


def test_existing_hook_still_runs_after_install(binder_repo):
    hook_file = manager.install(str(binder_repo))
    result = subprocess.run(
        [hook_file, str(binder_repo / "msg"), "message"],
        cwd=binder_repo,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0


def test_husky_public_hook_still_runs(tmp_path):
    repo = _husky_v9(tmp_path)
    hook_file = manager.install(str(repo))
    (repo / "msg").write_text("subject\n")
    result = subprocess.run(
        [hook_file, str(repo / "msg"), "message"],
        cwd=repo,
        capture_output=True,
        text=True,
    )

    assert f"public .husky/{HOOK}" in result.stdout


def test_symlinked_hook_is_not_written_through(tmp_path):
    repo = _overcommit(tmp_path)
    runner = repo / "overcommit-hook"
    before = runner.read_text()

    manager.install(str(repo))

    assert runner.read_text() == before
    assert manager.HOOK_MARKER_START not in (repo / ".git" / "hooks" / PUSH_HOOK).read_text()


def test_uninstall_restores_the_symlink(tmp_path):
    repo = _overcommit(tmp_path)
    hook_file = repo / ".git" / "hooks" / HOOK

    manager.install(str(repo))
    assert not hook_file.is_symlink()

    manager.uninstall(str(repo))

    assert hook_file.is_symlink()
    assert hook_file.resolve() == (repo / "overcommit-hook").resolve()
    assert not (repo / ".git" / "hooks" / manager._ORIGINAL_LINK_DIR).exists()


def test_symlinked_hook_preserves_argv0_dispatch(tmp_path):
    repo = _overcommit(tmp_path)
    hook_file = manager.install(str(repo))
    result = subprocess.run(
        [hook_file, str(repo / "msg"), "message"],
        cwd=repo,
        capture_output=True,
        text=True,
    )

    assert f"overcommit dispatch: {HOOK}" in result.stdout


# --- Attribution, end to end -------------------------------------------------


def _commit(repo: Path, message: str, agent: str | None) -> str:
    env = dict(os.environ)
    for var in ("AI_AGENT", "CLAUDE_CODE", "CURSOR_SESSION", "WINDSURF_SESSION"):
        env.pop(var, None)
    if agent:
        env[agent] = "1"

    (repo / f"file-{message.replace(' ', '-')}.txt").write_text(message)
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", message],
        cwd=repo,
        env=env,
        check=True,
        capture_output=True,
    )
    return subprocess.run(
        ["git", "log", "-1", "--format=%B"],
        cwd=repo,
        capture_output=True,
        text=True,
        check=True,
    ).stdout


def test_commit_is_attributed_on_every_binder(binder_repo):
    manager.install(str(binder_repo))
    body = _commit(binder_repo, "feat attributed", "CLAUDE_CODE")

    assert "Co-Authored-By: Claude Code" in body


def test_commit_without_agent_gets_no_trailer(binder_repo):
    manager.install(str(binder_repo))
    body = _commit(binder_repo, "feat human", None)

    assert "Co-Authored-By" not in body


def test_push_hook_does_not_fail_the_commit(binder_repo):
    manager.install(str(binder_repo))
    manager.install_push_hook(str(binder_repo))
    body = _commit(binder_repo, "feat with push hook", "CLAUDE_CODE")

    assert "Co-Authored-By: Claude Code" in body


# --- Payload and loader ------------------------------------------------------


def test_payload_is_deployed_outside_the_repo(binder_repo, iris_home):
    manager.install(str(binder_repo))

    assert (iris_home / "hooks" / HOOK).is_file()
    assert os.access(iris_home / "hooks" / HOOK, os.X_OK)


def test_repo_hook_carries_only_the_loader(binder_repo):
    hook_file = Path(manager.install(str(binder_repo)))
    content = hook_file.read_text()

    assert "IRIS_HOOK_PAYLOAD" in content
    assert "Detect AI agent" not in content


def test_payload_upgrade_needs_no_reinstall(binder_repo, iris_home):
    manager.install(str(binder_repo))
    hook_before = Path(manager.status(str(binder_repo))["hook_path"]).read_text()

    (iris_home / "hooks" / HOOK).write_text("#!/bin/sh\nexit 0\n")
    refreshed = manager.deploy_payloads()

    assert HOOK in refreshed
    assert Path(manager.status(str(binder_repo))["hook_path"]).read_text() == hook_before


def test_deploy_payloads_is_idempotent(iris_home):
    manager.deploy_payloads()

    assert manager.deploy_payloads() == []


# --- Stale sections ----------------------------------------------------------


def test_section_outside_the_resolved_dir_is_stale(tmp_path):
    repo = _husky_v9(tmp_path)
    stranded = repo / ".husky" / HOOK
    stranded.write_text(
        f'#!/usr/bin/env sh\n{manager.HOOK_MARKER_START}\nexit 0\n{manager.HOOK_MARKER_END}\n'
    )

    assert str(stranded) in manager.find_stale_sections(str(repo))
    assert str(stranded) in manager.status(str(repo))["stale_sections"]


def test_install_purges_stale_sections(tmp_path):
    repo = _husky_v9(tmp_path)
    stranded = repo / ".husky" / HOOK
    stranded.write_text(
        f'#!/usr/bin/env sh\necho keep\n{manager.HOOK_MARKER_START}\nexit 0\n{manager.HOOK_MARKER_END}\n'
    )

    manager.install(str(repo))

    assert manager.find_stale_sections(str(repo)) == []
    assert "echo keep" in stranded.read_text()


# --- Self-heal ---------------------------------------------------------------


def test_heal_restores_a_regenerated_hook(tmp_path):
    repo = _husky_v9(tmp_path)
    manager.install(str(repo))
    manager.install_push_hook(str(repo))

    _write(repo / ".husky" / "_" / HOOK, '#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n')
    assert not manager.probe_reachable(str(repo), HOOK)

    repaired = manager.heal(str(repo))

    assert HOOK in repaired
    assert manager.probe_reachable(str(repo), HOOK)


def test_heal_restores_a_deleted_hook_file(binder_repo):
    manager.install(str(binder_repo))
    hooks_dir = Path(manager.resolve_hooks_dir(str(binder_repo)))
    (hooks_dir / HOOK).unlink()

    assert HOOK in manager.heal(str(binder_repo))
    assert manager.probe_reachable(str(binder_repo), HOOK)


def test_heal_is_silent_when_healthy(binder_repo):
    manager.install(str(binder_repo))
    manager.install_push_hook(str(binder_repo))

    assert manager.heal(str(binder_repo)) == []


def test_heal_works_from_a_subdirectory(binder_repo):
    manager.install(str(binder_repo))
    hooks_dir = Path(manager.resolve_hooks_dir(str(binder_repo)))
    (hooks_dir / HOOK).unlink()

    nested = binder_repo / "src" / "deep"
    nested.mkdir(parents=True)

    assert HOOK in manager.heal(str(nested))
    assert manager.probe_reachable(str(binder_repo), HOOK)


def test_heal_ignores_unregistered_repos(tmp_path):
    repo = _init(tmp_path / "never-installed")

    assert manager.heal(str(repo)) == []
    assert not (repo / ".git" / "hooks" / HOOK).exists()


def test_uninstall_deregisters_so_heal_stops(binder_repo):
    manager.install(str(binder_repo))
    manager.install_push_hook(str(binder_repo))
    manager.uninstall(str(binder_repo))
    manager.uninstall_push_hook(str(binder_repo))

    assert manager.heal(str(binder_repo)) == []
    assert not manager.probe_reachable(str(binder_repo), HOOK)


# --- Install / uninstall lifecycle -------------------------------------------


def test_second_install_reports_already_installed(binder_repo):
    manager.install(str(binder_repo))

    with pytest.raises(FileExistsError):
        manager.install(str(binder_repo))


def test_uninstall_preserves_the_library_hook(binder_repo):
    hooks_dir = Path(manager.resolve_hooks_dir(str(binder_repo)))
    hook_file = hooks_dir / HOOK
    before = hook_file.read_text() if hook_file.is_file() else None

    manager.install(str(binder_repo))
    manager.uninstall(str(binder_repo))

    if before is None:
        assert not hook_file.exists()
    else:
        assert hook_file.read_text() == before


def test_uninstall_reports_nothing_when_absent(binder_repo):
    assert manager.uninstall(str(binder_repo)) is False
